// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_service

import (
	"context"
	"github.com/wrzdx/Nero/internal/core/auth"
	"github.com/wrzdx/Nero/internal/core/domain"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionsRepository creates a new instance of MockSessionsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionsRepository {
	mock := &MockSessionsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionsRepository is an autogenerated mock type for the SessionsRepository type
type MockSessionsRepository struct {
	mock.Mock
}

type MockSessionsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionsRepository) EXPECT() *MockSessionsRepository_Expecter {
	return &MockSessionsRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionsRepository
func (_mock *MockSessionsRepository) CreateSession(ctx context.Context, session domain.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionsRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionsRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session domain.Session
func (_e *MockSessionsRepository_Expecter) CreateSession(ctx any, session any) *MockSessionsRepository_CreateSession_Call {
	return &MockSessionsRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session)}
}

func (_c *MockSessionsRepository_CreateSession_Call) Run(run func(ctx context.Context, session domain.Session)) *MockSessionsRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Session
		if args[1] != nil {
			arg1 = args[1].(domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionsRepository_CreateSession_Call) Return(err error) *MockSessionsRepository_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionsRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, session domain.Session) error) *MockSessionsRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllSessions provides a mock function for the type MockSessionsRepository
func (_mock *MockSessionsRepository) DeleteAllSessions(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionsRepository_DeleteAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllSessions'
type MockSessionsRepository_DeleteAllSessions_Call struct {
	*mock.Call
}

// DeleteAllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSessionsRepository_Expecter) DeleteAllSessions(ctx any, userID any) *MockSessionsRepository_DeleteAllSessions_Call {
	return &MockSessionsRepository_DeleteAllSessions_Call{Call: _e.mock.On("DeleteAllSessions", ctx, userID)}
}

func (_c *MockSessionsRepository_DeleteAllSessions_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSessionsRepository_DeleteAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionsRepository_DeleteAllSessions_Call) Return(err error) *MockSessionsRepository_DeleteAllSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionsRepository_DeleteAllSessions_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockSessionsRepository_DeleteAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockSessionsRepository
func (_mock *MockSessionsRepository) DeleteSession(ctx context.Context, sessionID uuid.UUID, currentTokenID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionID, currentTokenID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionID, currentTokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionsRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionsRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - currentTokenID uuid.UUID
func (_e *MockSessionsRepository_Expecter) DeleteSession(ctx any, sessionID any, currentTokenID any) *MockSessionsRepository_DeleteSession_Call {
	return &MockSessionsRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionID, currentTokenID)}
}

func (_c *MockSessionsRepository_DeleteSession_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, currentTokenID uuid.UUID)) *MockSessionsRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionsRepository_DeleteSession_Call) Return(err error) *MockSessionsRepository_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionsRepository_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, currentTokenID uuid.UUID) error) *MockSessionsRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// RotateSession provides a mock function for the type MockSessionsRepository
func (_mock *MockSessionsRepository) RotateSession(ctx context.Context, sessionID uuid.UUID, currentTokenID uuid.UUID, newTokenID uuid.UUID, usedAt time.Time) (domain.Session, error) {
	ret := _mock.Called(ctx, sessionID, currentTokenID, newTokenID, usedAt)

	if len(ret) == 0 {
		panic("no return value specified for RotateSession")
	}

	var r0 domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, time.Time) (domain.Session, error)); ok {
		return returnFunc(ctx, sessionID, currentTokenID, newTokenID, usedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, time.Time) domain.Session); ok {
		r0 = returnFunc(ctx, sessionID, currentTokenID, newTokenID, usedAt)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, sessionID, currentTokenID, newTokenID, usedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionsRepository_RotateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateSession'
type MockSessionsRepository_RotateSession_Call struct {
	*mock.Call
}

// RotateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - currentTokenID uuid.UUID
//   - newTokenID uuid.UUID
//   - usedAt time.Time
func (_e *MockSessionsRepository_Expecter) RotateSession(ctx any, sessionID any, currentTokenID any, newTokenID any, usedAt any) *MockSessionsRepository_RotateSession_Call {
	return &MockSessionsRepository_RotateSession_Call{Call: _e.mock.On("RotateSession", ctx, sessionID, currentTokenID, newTokenID, usedAt)}
}

func (_c *MockSessionsRepository_RotateSession_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, currentTokenID uuid.UUID, newTokenID uuid.UUID, usedAt time.Time)) *MockSessionsRepository_RotateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSessionsRepository_RotateSession_Call) Return(session domain.Session, err error) *MockSessionsRepository_RotateSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionsRepository_RotateSession_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, currentTokenID uuid.UUID, newTokenID uuid.UUID, usedAt time.Time) (domain.Session, error)) *MockSessionsRepository_RotateSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) ChangePassword(ctx context.Context, id uuid.UUID, newPasswordHash string, currentPasswordHash string) error {
	ret := _mock.Called(ctx, id, newPasswordHash, currentPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, id, newPasswordHash, currentPasswordHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockUsersRepository_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - newPasswordHash string
//   - currentPasswordHash string
func (_e *MockUsersRepository_Expecter) ChangePassword(ctx any, id any, newPasswordHash any, currentPasswordHash any) *MockUsersRepository_ChangePassword_Call {
	return &MockUsersRepository_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, id, newPasswordHash, currentPasswordHash)}
}

func (_c *MockUsersRepository_ChangePassword_Call) Run(run func(ctx context.Context, id uuid.UUID, newPasswordHash string, currentPasswordHash string)) *MockUsersRepository_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersRepository_ChangePassword_Call) Return(err error) *MockUsersRepository_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, newPasswordHash string, currentPasswordHash string) error) *MockUsersRepository_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) CreateUser(ctx context.Context, user domain.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUsersRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockUsersRepository_Expecter) CreateUser(ctx any, user any) *MockUsersRepository_CreateUser_Call {
	return &MockUsersRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUsersRepository_CreateUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockUsersRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) Return(err error) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) error) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUser(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUsersRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsersRepository_Expecter) GetUser(ctx any, id any) *MockUsersRepository_GetUser_Call {
	return &MockUsersRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUsersRepository_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUser_Call) Return(user domain.User, err error) *MockUsersRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.User, error)) *MockUsersRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserByUsername(ctx context.Context, username string) (domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUsersRepository_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUsersRepository_Expecter) GetUserByUsername(ctx any, username any) *MockUsersRepository_GetUserByUsername_Call {
	return &MockUsersRepository_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockUsersRepository_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserByUsername_Call) Return(user domain.User, err error) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (domain.User, error)) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserForUpdate provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserForUpdate(ctx context.Context, userID uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserForUpdate")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserForUpdate'
type MockUsersRepository_GetUserForUpdate_Call struct {
	*mock.Call
}

// GetUserForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUsersRepository_Expecter) GetUserForUpdate(ctx any, userID any) *MockUsersRepository_GetUserForUpdate_Call {
	return &MockUsersRepository_GetUserForUpdate_Call{Call: _e.mock.On("GetUserForUpdate", ctx, userID)}
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) Return(user domain.User, err error) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (domain.User, error)) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type MockHasher
func (_mock *MockHasher) Compare(hash string, password string) error {
	ret := _mock.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hash, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockHasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *MockHasher_Expecter) Compare(hash any, password any) *MockHasher_Compare_Call {
	return &MockHasher_Compare_Call{Call: _e.mock.On("Compare", hash, password)}
}

func (_c *MockHasher_Compare_Call) Run(run func(hash string, password string)) *MockHasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHasher_Compare_Call) Return(err error) *MockHasher_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHasher_Compare_Call) RunAndReturn(run func(hash string, password string) error) *MockHasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// DummyCompare provides a mock function for the type MockHasher
func (_mock *MockHasher) DummyCompare() {
	_mock.Called()
	return
}

// MockHasher_DummyCompare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DummyCompare'
type MockHasher_DummyCompare_Call struct {
	*mock.Call
}

// DummyCompare is a helper method to define mock.On call
func (_e *MockHasher_Expecter) DummyCompare() *MockHasher_DummyCompare_Call {
	return &MockHasher_DummyCompare_Call{Call: _e.mock.On("DummyCompare")}
}

func (_c *MockHasher_DummyCompare_Call) Run(run func()) *MockHasher_DummyCompare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHasher_DummyCompare_Call) Return() *MockHasher_DummyCompare_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHasher_DummyCompare_Call) RunAndReturn(run func()) *MockHasher_DummyCompare_Call {
	_c.Run(run)
	return _c
}

// Hash provides a mock function for the type MockHasher
func (_mock *MockHasher) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *MockHasher_Expecter) Hash(password any) *MockHasher_Hash_Call {
	return &MockHasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *MockHasher_Hash_Call) Run(run func(password string)) *MockHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHasher_Hash_Call) Return(s string, err error) *MockHasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHasher_Hash_Call) RunAndReturn(run func(password string) (string, error)) *MockHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenProvider creates a new instance of MockTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenProvider {
	mock := &MockTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenProvider is an autogenerated mock type for the TokenProvider type
type MockTokenProvider struct {
	mock.Mock
}

type MockTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenProvider) EXPECT() *MockTokenProvider_Expecter {
	return &MockTokenProvider_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) GenerateAccessToken(accessTokenClaims auth.AccessTokenClaims, tokenLifetime auth.TokenLifetime) (string, error) {
	ret := _mock.Called(accessTokenClaims, tokenLifetime)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(auth.AccessTokenClaims, auth.TokenLifetime) (string, error)); ok {
		return returnFunc(accessTokenClaims, tokenLifetime)
	}
	if returnFunc, ok := ret.Get(0).(func(auth.AccessTokenClaims, auth.TokenLifetime) string); ok {
		r0 = returnFunc(accessTokenClaims, tokenLifetime)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(auth.AccessTokenClaims, auth.TokenLifetime) error); ok {
		r1 = returnFunc(accessTokenClaims, tokenLifetime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenProvider_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - accessTokenClaims auth.AccessTokenClaims
//   - tokenLifetime auth.TokenLifetime
func (_e *MockTokenProvider_Expecter) GenerateAccessToken(accessTokenClaims any, tokenLifetime any) *MockTokenProvider_GenerateAccessToken_Call {
	return &MockTokenProvider_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", accessTokenClaims, tokenLifetime)}
}

func (_c *MockTokenProvider_GenerateAccessToken_Call) Run(run func(accessTokenClaims auth.AccessTokenClaims, tokenLifetime auth.TokenLifetime)) *MockTokenProvider_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 auth.AccessTokenClaims
		if args[0] != nil {
			arg0 = args[0].(auth.AccessTokenClaims)
		}
		var arg1 auth.TokenLifetime
		if args[1] != nil {
			arg1 = args[1].(auth.TokenLifetime)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenProvider_GenerateAccessToken_Call) Return(s string, err error) *MockTokenProvider_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenProvider_GenerateAccessToken_Call) RunAndReturn(run func(accessTokenClaims auth.AccessTokenClaims, tokenLifetime auth.TokenLifetime) (string, error)) *MockTokenProvider_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) GenerateRefreshToken(refreshTokenClaims auth.RefreshTokenClaims, tokenLifetime auth.TokenLifetime) (string, error) {
	ret := _mock.Called(refreshTokenClaims, tokenLifetime)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(auth.RefreshTokenClaims, auth.TokenLifetime) (string, error)); ok {
		return returnFunc(refreshTokenClaims, tokenLifetime)
	}
	if returnFunc, ok := ret.Get(0).(func(auth.RefreshTokenClaims, auth.TokenLifetime) string); ok {
		r0 = returnFunc(refreshTokenClaims, tokenLifetime)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(auth.RefreshTokenClaims, auth.TokenLifetime) error); ok {
		r1 = returnFunc(refreshTokenClaims, tokenLifetime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenProvider_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - refreshTokenClaims auth.RefreshTokenClaims
//   - tokenLifetime auth.TokenLifetime
func (_e *MockTokenProvider_Expecter) GenerateRefreshToken(refreshTokenClaims any, tokenLifetime any) *MockTokenProvider_GenerateRefreshToken_Call {
	return &MockTokenProvider_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", refreshTokenClaims, tokenLifetime)}
}

func (_c *MockTokenProvider_GenerateRefreshToken_Call) Run(run func(refreshTokenClaims auth.RefreshTokenClaims, tokenLifetime auth.TokenLifetime)) *MockTokenProvider_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 auth.RefreshTokenClaims
		if args[0] != nil {
			arg0 = args[0].(auth.RefreshTokenClaims)
		}
		var arg1 auth.TokenLifetime
		if args[1] != nil {
			arg1 = args[1].(auth.TokenLifetime)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenProvider_GenerateRefreshToken_Call) Return(s string, err error) *MockTokenProvider_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenProvider_GenerateRefreshToken_Call) RunAndReturn(run func(refreshTokenClaims auth.RefreshTokenClaims, tokenLifetime auth.TokenLifetime) (string, error)) *MockTokenProvider_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRefreshToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) ParseRefreshToken(tokenStr string) (auth.RefreshTokenClaims, error) {
	ret := _mock.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefreshToken")
	}

	var r0 auth.RefreshTokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (auth.RefreshTokenClaims, error)); ok {
		return returnFunc(tokenStr)
	}
	if returnFunc, ok := ret.Get(0).(func(string) auth.RefreshTokenClaims); ok {
		r0 = returnFunc(tokenStr)
	} else {
		r0 = ret.Get(0).(auth.RefreshTokenClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_ParseRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRefreshToken'
type MockTokenProvider_ParseRefreshToken_Call struct {
	*mock.Call
}

// ParseRefreshToken is a helper method to define mock.On call
//   - tokenStr string
func (_e *MockTokenProvider_Expecter) ParseRefreshToken(tokenStr any) *MockTokenProvider_ParseRefreshToken_Call {
	return &MockTokenProvider_ParseRefreshToken_Call{Call: _e.mock.On("ParseRefreshToken", tokenStr)}
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) Run(run func(tokenStr string)) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) Return(refreshTokenClaims auth.RefreshTokenClaims, err error) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Return(refreshTokenClaims, err)
	return _c
}

func (_c *MockTokenProvider_ParseRefreshToken_Call) RunAndReturn(run func(tokenStr string) (auth.RefreshTokenClaims, error)) *MockTokenProvider_ParseRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTXManager creates a new instance of MockTXManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTXManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTXManager {
	mock := &MockTXManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTXManager is an autogenerated mock type for the TXManager type
type MockTXManager struct {
	mock.Mock
}

type MockTXManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTXManager) EXPECT() *MockTXManager_Expecter {
	return &MockTXManager_Expecter{mock: &_m.Mock}
}

// WithinTransaction provides a mock function for the type MockTXManager
func (_mock *MockTXManager) WithinTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTXManager_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockTXManager_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTXManager_Expecter) WithinTransaction(ctx any, fn any) *MockTXManager_WithinTransaction_Call {
	return &MockTXManager_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, fn)}
}

func (_c *MockTXManager_WithinTransaction_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTXManager_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) Return(err error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}
