// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chats_service

import (
	"context"
	"github.com/wrzdx/Nero/internal/core/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatsRepository creates a new instance of MockChatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatsRepository {
	mock := &MockChatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatsRepository is an autogenerated mock type for the ChatsRepository type
type MockChatsRepository struct {
	mock.Mock
}

type MockChatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatsRepository) EXPECT() *MockChatsRepository_Expecter {
	return &MockChatsRepository_Expecter{mock: &_m.Mock}
}

// AddGroupParticipants provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) AddGroupParticipants(ctx context.Context, groupID uuid.UUID, participants []domain.GroupParticipant) ([]bool, error) {
	ret := _mock.Called(ctx, groupID, participants)

	if len(ret) == 0 {
		panic("no return value specified for AddGroupParticipants")
	}

	var r0 []bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []domain.GroupParticipant) ([]bool, error)); ok {
		return returnFunc(ctx, groupID, participants)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []domain.GroupParticipant) []bool); ok {
		r0 = returnFunc(ctx, groupID, participants)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []domain.GroupParticipant) error); ok {
		r1 = returnFunc(ctx, groupID, participants)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_AddGroupParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGroupParticipants'
type MockChatsRepository_AddGroupParticipants_Call struct {
	*mock.Call
}

// AddGroupParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - participants []domain.GroupParticipant
func (_e *MockChatsRepository_Expecter) AddGroupParticipants(ctx any, groupID any, participants any) *MockChatsRepository_AddGroupParticipants_Call {
	return &MockChatsRepository_AddGroupParticipants_Call{Call: _e.mock.On("AddGroupParticipants", ctx, groupID, participants)}
}

func (_c *MockChatsRepository_AddGroupParticipants_Call) Run(run func(ctx context.Context, groupID uuid.UUID, participants []domain.GroupParticipant)) *MockChatsRepository_AddGroupParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []domain.GroupParticipant
		if args[2] != nil {
			arg2 = args[2].([]domain.GroupParticipant)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsRepository_AddGroupParticipants_Call) Return(bools []bool, err error) *MockChatsRepository_AddGroupParticipants_Call {
	_c.Call.Return(bools, err)
	return _c
}

func (_c *MockChatsRepository_AddGroupParticipants_Call) RunAndReturn(run func(ctx context.Context, groupID uuid.UUID, participants []domain.GroupParticipant) ([]bool, error)) *MockChatsRepository_AddGroupParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDirect provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) CreateDirect(ctx context.Context, direct domain.DirectChat, participant1 domain.ChatParticipant, participant2 domain.ChatParticipant) error {
	ret := _mock.Called(ctx, direct, participant1, participant2)

	if len(ret) == 0 {
		panic("no return value specified for CreateDirect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DirectChat, domain.ChatParticipant, domain.ChatParticipant) error); ok {
		r0 = returnFunc(ctx, direct, participant1, participant2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatsRepository_CreateDirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDirect'
type MockChatsRepository_CreateDirect_Call struct {
	*mock.Call
}

// CreateDirect is a helper method to define mock.On call
//   - ctx context.Context
//   - direct domain.DirectChat
//   - participant1 domain.ChatParticipant
//   - participant2 domain.ChatParticipant
func (_e *MockChatsRepository_Expecter) CreateDirect(ctx any, direct any, participant1 any, participant2 any) *MockChatsRepository_CreateDirect_Call {
	return &MockChatsRepository_CreateDirect_Call{Call: _e.mock.On("CreateDirect", ctx, direct, participant1, participant2)}
}

func (_c *MockChatsRepository_CreateDirect_Call) Run(run func(ctx context.Context, direct domain.DirectChat, participant1 domain.ChatParticipant, participant2 domain.ChatParticipant)) *MockChatsRepository_CreateDirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DirectChat
		if args[1] != nil {
			arg1 = args[1].(domain.DirectChat)
		}
		var arg2 domain.ChatParticipant
		if args[2] != nil {
			arg2 = args[2].(domain.ChatParticipant)
		}
		var arg3 domain.ChatParticipant
		if args[3] != nil {
			arg3 = args[3].(domain.ChatParticipant)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockChatsRepository_CreateDirect_Call) Return(err error) *MockChatsRepository_CreateDirect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatsRepository_CreateDirect_Call) RunAndReturn(run func(ctx context.Context, direct domain.DirectChat, participant1 domain.ChatParticipant, participant2 domain.ChatParticipant) error) *MockChatsRepository_CreateDirect_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) CreateGroup(ctx context.Context, group domain.GroupChat, participants []domain.GroupParticipant) error {
	ret := _mock.Called(ctx, group, participants)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GroupChat, []domain.GroupParticipant) error); ok {
		r0 = returnFunc(ctx, group, participants)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatsRepository_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockChatsRepository_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - group domain.GroupChat
//   - participants []domain.GroupParticipant
func (_e *MockChatsRepository_Expecter) CreateGroup(ctx any, group any, participants any) *MockChatsRepository_CreateGroup_Call {
	return &MockChatsRepository_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, group, participants)}
}

func (_c *MockChatsRepository_CreateGroup_Call) Run(run func(ctx context.Context, group domain.GroupChat, participants []domain.GroupParticipant)) *MockChatsRepository_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GroupChat
		if args[1] != nil {
			arg1 = args[1].(domain.GroupChat)
		}
		var arg2 []domain.GroupParticipant
		if args[2] != nil {
			arg2 = args[2].([]domain.GroupParticipant)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsRepository_CreateGroup_Call) Return(err error) *MockChatsRepository_CreateGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatsRepository_CreateGroup_Call) RunAndReturn(run func(ctx context.Context, group domain.GroupChat, participants []domain.GroupParticipant) error) *MockChatsRepository_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetDirectByUsers provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) GetDirectByUsers(ctx context.Context, user1ID uuid.UUID, user2ID uuid.UUID) (domain.DirectChat, error) {
	ret := _mock.Called(ctx, user1ID, user2ID)

	if len(ret) == 0 {
		panic("no return value specified for GetDirectByUsers")
	}

	var r0 domain.DirectChat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.DirectChat, error)); ok {
		return returnFunc(ctx, user1ID, user2ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.DirectChat); ok {
		r0 = returnFunc(ctx, user1ID, user2ID)
	} else {
		r0 = ret.Get(0).(domain.DirectChat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, user1ID, user2ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_GetDirectByUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDirectByUsers'
type MockChatsRepository_GetDirectByUsers_Call struct {
	*mock.Call
}

// GetDirectByUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - user1ID uuid.UUID
//   - user2ID uuid.UUID
func (_e *MockChatsRepository_Expecter) GetDirectByUsers(ctx any, user1ID any, user2ID any) *MockChatsRepository_GetDirectByUsers_Call {
	return &MockChatsRepository_GetDirectByUsers_Call{Call: _e.mock.On("GetDirectByUsers", ctx, user1ID, user2ID)}
}

func (_c *MockChatsRepository_GetDirectByUsers_Call) Run(run func(ctx context.Context, user1ID uuid.UUID, user2ID uuid.UUID)) *MockChatsRepository_GetDirectByUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsRepository_GetDirectByUsers_Call) Return(directChat domain.DirectChat, err error) *MockChatsRepository_GetDirectByUsers_Call {
	_c.Call.Return(directChat, err)
	return _c
}

func (_c *MockChatsRepository_GetDirectByUsers_Call) RunAndReturn(run func(ctx context.Context, user1ID uuid.UUID, user2ID uuid.UUID) (domain.DirectChat, error)) *MockChatsRepository_GetDirectByUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroup provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) GetGroup(ctx context.Context, groupID uuid.UUID) (domain.GroupChat, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroup")
	}

	var r0 domain.GroupChat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.GroupChat, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.GroupChat); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		r0 = ret.Get(0).(domain.GroupChat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_GetGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroup'
type MockChatsRepository_GetGroup_Call struct {
	*mock.Call
}

// GetGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
func (_e *MockChatsRepository_Expecter) GetGroup(ctx any, groupID any) *MockChatsRepository_GetGroup_Call {
	return &MockChatsRepository_GetGroup_Call{Call: _e.mock.On("GetGroup", ctx, groupID)}
}

func (_c *MockChatsRepository_GetGroup_Call) Run(run func(ctx context.Context, groupID uuid.UUID)) *MockChatsRepository_GetGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatsRepository_GetGroup_Call) Return(groupChat domain.GroupChat, err error) *MockChatsRepository_GetGroup_Call {
	_c.Call.Return(groupChat, err)
	return _c
}

func (_c *MockChatsRepository_GetGroup_Call) RunAndReturn(run func(ctx context.Context, groupID uuid.UUID) (domain.GroupChat, error)) *MockChatsRepository_GetGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupParticipant provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) GetGroupParticipant(ctx context.Context, chatID uuid.UUID, userID uuid.UUID) (domain.GroupParticipant, error) {
	ret := _mock.Called(ctx, chatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupParticipant")
	}

	var r0 domain.GroupParticipant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.GroupParticipant, error)); ok {
		return returnFunc(ctx, chatID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.GroupParticipant); ok {
		r0 = returnFunc(ctx, chatID, userID)
	} else {
		r0 = ret.Get(0).(domain.GroupParticipant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, chatID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_GetGroupParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupParticipant'
type MockChatsRepository_GetGroupParticipant_Call struct {
	*mock.Call
}

// GetGroupParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - userID uuid.UUID
func (_e *MockChatsRepository_Expecter) GetGroupParticipant(ctx any, chatID any, userID any) *MockChatsRepository_GetGroupParticipant_Call {
	return &MockChatsRepository_GetGroupParticipant_Call{Call: _e.mock.On("GetGroupParticipant", ctx, chatID, userID)}
}

func (_c *MockChatsRepository_GetGroupParticipant_Call) Run(run func(ctx context.Context, chatID uuid.UUID, userID uuid.UUID)) *MockChatsRepository_GetGroupParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsRepository_GetGroupParticipant_Call) Return(groupParticipant domain.GroupParticipant, err error) *MockChatsRepository_GetGroupParticipant_Call {
	_c.Call.Return(groupParticipant, err)
	return _c
}

func (_c *MockChatsRepository_GetGroupParticipant_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, userID uuid.UUID) (domain.GroupParticipant, error)) *MockChatsRepository_GetGroupParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantsStatus provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) GetParticipantsStatus(ctx context.Context, userIDs []uuid.UUID) ([]ParticipantStatus, error) {
	ret := _mock.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantsStatus")
	}

	var r0 []ParticipantStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]ParticipantStatus, error)); ok {
		return returnFunc(ctx, userIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []ParticipantStatus); ok {
		r0 = returnFunc(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ParticipantStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_GetParticipantsStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantsStatus'
type MockChatsRepository_GetParticipantsStatus_Call struct {
	*mock.Call
}

// GetParticipantsStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []uuid.UUID
func (_e *MockChatsRepository_Expecter) GetParticipantsStatus(ctx any, userIDs any) *MockChatsRepository_GetParticipantsStatus_Call {
	return &MockChatsRepository_GetParticipantsStatus_Call{Call: _e.mock.On("GetParticipantsStatus", ctx, userIDs)}
}

func (_c *MockChatsRepository_GetParticipantsStatus_Call) Run(run func(ctx context.Context, userIDs []uuid.UUID)) *MockChatsRepository_GetParticipantsStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatsRepository_GetParticipantsStatus_Call) Return(participantStatuss []ParticipantStatus, err error) *MockChatsRepository_GetParticipantsStatus_Call {
	_c.Call.Return(participantStatuss, err)
	return _c
}

func (_c *MockChatsRepository_GetParticipantsStatus_Call) RunAndReturn(run func(ctx context.Context, userIDs []uuid.UUID) ([]ParticipantStatus, error)) *MockChatsRepository_GetParticipantsStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListChats provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) ListChats(ctx context.Context, userID uuid.UUID, before *ChatCursor, limit int) ([]ChatItem, error) {
	ret := _mock.Called(ctx, userID, before, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListChats")
	}

	var r0 []ChatItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *ChatCursor, int) ([]ChatItem, error)); ok {
		return returnFunc(ctx, userID, before, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *ChatCursor, int) []ChatItem); ok {
		r0 = returnFunc(ctx, userID, before, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ChatItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *ChatCursor, int) error); ok {
		r1 = returnFunc(ctx, userID, before, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_ListChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListChats'
type MockChatsRepository_ListChats_Call struct {
	*mock.Call
}

// ListChats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - before *ChatCursor
//   - limit int
func (_e *MockChatsRepository_Expecter) ListChats(ctx any, userID any, before any, limit any) *MockChatsRepository_ListChats_Call {
	return &MockChatsRepository_ListChats_Call{Call: _e.mock.On("ListChats", ctx, userID, before, limit)}
}

func (_c *MockChatsRepository_ListChats_Call) Run(run func(ctx context.Context, userID uuid.UUID, before *ChatCursor, limit int)) *MockChatsRepository_ListChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *ChatCursor
		if args[2] != nil {
			arg2 = args[2].(*ChatCursor)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockChatsRepository_ListChats_Call) Return(chatItems []ChatItem, err error) *MockChatsRepository_ListChats_Call {
	_c.Call.Return(chatItems, err)
	return _c
}

func (_c *MockChatsRepository_ListChats_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, before *ChatCursor, limit int) ([]ChatItem, error)) *MockChatsRepository_ListChats_Call {
	_c.Call.Return(run)
	return _c
}

// ListGroupParticipants provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) ListGroupParticipants(ctx context.Context, chatID uuid.UUID, before *GroupParticipantCursor, limit int) ([]ParticipantInfo, error) {
	ret := _mock.Called(ctx, chatID, before, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupParticipants")
	}

	var r0 []ParticipantInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *GroupParticipantCursor, int) ([]ParticipantInfo, error)); ok {
		return returnFunc(ctx, chatID, before, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *GroupParticipantCursor, int) []ParticipantInfo); ok {
		r0 = returnFunc(ctx, chatID, before, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ParticipantInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *GroupParticipantCursor, int) error); ok {
		r1 = returnFunc(ctx, chatID, before, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_ListGroupParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroupParticipants'
type MockChatsRepository_ListGroupParticipants_Call struct {
	*mock.Call
}

// ListGroupParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - before *GroupParticipantCursor
//   - limit int
func (_e *MockChatsRepository_Expecter) ListGroupParticipants(ctx any, chatID any, before any, limit any) *MockChatsRepository_ListGroupParticipants_Call {
	return &MockChatsRepository_ListGroupParticipants_Call{Call: _e.mock.On("ListGroupParticipants", ctx, chatID, before, limit)}
}

func (_c *MockChatsRepository_ListGroupParticipants_Call) Run(run func(ctx context.Context, chatID uuid.UUID, before *GroupParticipantCursor, limit int)) *MockChatsRepository_ListGroupParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *GroupParticipantCursor
		if args[2] != nil {
			arg2 = args[2].(*GroupParticipantCursor)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockChatsRepository_ListGroupParticipants_Call) Return(participantInfos []ParticipantInfo, err error) *MockChatsRepository_ListGroupParticipants_Call {
	_c.Call.Return(participantInfos, err)
	return _c
}

func (_c *MockChatsRepository_ListGroupParticipants_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, before *GroupParticipantCursor, limit int) ([]ParticipantInfo, error)) *MockChatsRepository_ListGroupParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGroupParticipant provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) RemoveGroupParticipant(ctx context.Context, participant domain.GroupParticipant) error {
	ret := _mock.Called(ctx, participant)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGroupParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GroupParticipant) error); ok {
		r0 = returnFunc(ctx, participant)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatsRepository_RemoveGroupParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGroupParticipant'
type MockChatsRepository_RemoveGroupParticipant_Call struct {
	*mock.Call
}

// RemoveGroupParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - participant domain.GroupParticipant
func (_e *MockChatsRepository_Expecter) RemoveGroupParticipant(ctx any, participant any) *MockChatsRepository_RemoveGroupParticipant_Call {
	return &MockChatsRepository_RemoveGroupParticipant_Call{Call: _e.mock.On("RemoveGroupParticipant", ctx, participant)}
}

func (_c *MockChatsRepository_RemoveGroupParticipant_Call) Run(run func(ctx context.Context, participant domain.GroupParticipant)) *MockChatsRepository_RemoveGroupParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GroupParticipant
		if args[1] != nil {
			arg1 = args[1].(domain.GroupParticipant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatsRepository_RemoveGroupParticipant_Call) Return(err error) *MockChatsRepository_RemoveGroupParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatsRepository_RemoveGroupParticipant_Call) RunAndReturn(run func(ctx context.Context, participant domain.GroupParticipant) error) *MockChatsRepository_RemoveGroupParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) UpdateGroup(ctx context.Context, updated domain.GroupChat) error {
	ret := _mock.Called(ctx, updated)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GroupChat) error); ok {
		r0 = returnFunc(ctx, updated)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatsRepository_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockChatsRepository_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - updated domain.GroupChat
func (_e *MockChatsRepository_Expecter) UpdateGroup(ctx any, updated any) *MockChatsRepository_UpdateGroup_Call {
	return &MockChatsRepository_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, updated)}
}

func (_c *MockChatsRepository_UpdateGroup_Call) Run(run func(ctx context.Context, updated domain.GroupChat)) *MockChatsRepository_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GroupChat
		if args[1] != nil {
			arg1 = args[1].(domain.GroupChat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatsRepository_UpdateGroup_Call) Return(err error) *MockChatsRepository_UpdateGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatsRepository_UpdateGroup_Call) RunAndReturn(run func(ctx context.Context, updated domain.GroupChat) error) *MockChatsRepository_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTXManager creates a new instance of MockTXManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTXManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTXManager {
	mock := &MockTXManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTXManager is an autogenerated mock type for the TXManager type
type MockTXManager struct {
	mock.Mock
}

type MockTXManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTXManager) EXPECT() *MockTXManager_Expecter {
	return &MockTXManager_Expecter{mock: &_m.Mock}
}

// WithinTransaction provides a mock function for the type MockTXManager
func (_mock *MockTXManager) WithinTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTXManager_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockTXManager_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTXManager_Expecter) WithinTransaction(ctx any, fn any) *MockTXManager_WithinTransaction_Call {
	return &MockTXManager_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, fn)}
}

func (_c *MockTXManager_WithinTransaction_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTXManager_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) Return(err error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// GetUserByUsername provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserByUsername(ctx context.Context, username string) (domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUsersRepository_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUsersRepository_Expecter) GetUserByUsername(ctx any, username any) *MockUsersRepository_GetUserByUsername_Call {
	return &MockUsersRepository_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockUsersRepository_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserByUsername_Call) Return(user domain.User, err error) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (domain.User, error)) *MockUsersRepository_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserForUpdate provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserForUpdate(ctx context.Context, userID uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserForUpdate")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserForUpdate'
type MockUsersRepository_GetUserForUpdate_Call struct {
	*mock.Call
}

// GetUserForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUsersRepository_Expecter) GetUserForUpdate(ctx any, userID any) *MockUsersRepository_GetUserForUpdate_Call {
	return &MockUsersRepository_GetUserForUpdate_Call{Call: _e.mock.On("GetUserForUpdate", ctx, userID)}
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) Return(user domain.User, err error) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (domain.User, error)) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Return(run)
	return _c
}
