// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package users_transport_http

import (
	"context"
	"github.com/wrzdx/Nero/internal/core/domain"
	"github.com/wrzdx/Nero/internal/features/users/service"
	"net/http"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsersService creates a new instance of MockUsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersService {
	mock := &MockUsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersService is an autogenerated mock type for the UsersService type
type MockUsersService struct {
	mock.Mock
}

type MockUsersService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersService) EXPECT() *MockUsersService_Expecter {
	return &MockUsersService_Expecter{mock: &_m.Mock}
}

// DeleteAccount provides a mock function for the type MockUsersService
func (_mock *MockUsersService) DeleteAccount(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersService_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockUsersService_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUsersService_Expecter) DeleteAccount(ctx any, userID any) *MockUsersService_DeleteAccount_Call {
	return &MockUsersService_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, userID)}
}

func (_c *MockUsersService_DeleteAccount_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUsersService_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersService_DeleteAccount_Call) Return(err error) *MockUsersService_DeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersService_DeleteAccount_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockUsersService_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUsersService
func (_mock *MockUsersService) GetUser(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUsersService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsersService_Expecter) GetUser(ctx any, id any) *MockUsersService_GetUser_Call {
	return &MockUsersService_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUsersService_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersService_GetUser_Call) Return(user domain.User, err error) *MockUsersService_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersService_GetUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.User, error)) *MockUsersService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function for the type MockUsersService
func (_mock *MockUsersService) SearchUsers(ctx context.Context, requesterID uuid.UUID, query users_service.SearchUsersQuery) ([]users_service.UserSearchResult, error) {
	ret := _mock.Called(ctx, requesterID, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []users_service.UserSearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, users_service.SearchUsersQuery) ([]users_service.UserSearchResult, error)); ok {
		return returnFunc(ctx, requesterID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, users_service.SearchUsersQuery) []users_service.UserSearchResult); ok {
		r0 = returnFunc(ctx, requesterID, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users_service.UserSearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, users_service.SearchUsersQuery) error); ok {
		r1 = returnFunc(ctx, requesterID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersService_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockUsersService_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - requesterID uuid.UUID
//   - query users_service.SearchUsersQuery
func (_e *MockUsersService_Expecter) SearchUsers(ctx any, requesterID any, query any) *MockUsersService_SearchUsers_Call {
	return &MockUsersService_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, requesterID, query)}
}

func (_c *MockUsersService_SearchUsers_Call) Run(run func(ctx context.Context, requesterID uuid.UUID, query users_service.SearchUsersQuery)) *MockUsersService_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 users_service.SearchUsersQuery
		if args[2] != nil {
			arg2 = args[2].(users_service.SearchUsersQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersService_SearchUsers_Call) Return(userSearchResults []users_service.UserSearchResult, err error) *MockUsersService_SearchUsers_Call {
	_c.Call.Return(userSearchResults, err)
	return _c
}

func (_c *MockUsersService_SearchUsers_Call) RunAndReturn(run func(ctx context.Context, requesterID uuid.UUID, query users_service.SearchUsersQuery) ([]users_service.UserSearchResult, error)) *MockUsersService_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockUsersService
func (_mock *MockUsersService) UpdateProfile(ctx context.Context, userID uuid.UUID, command users_service.UpdateProfileCommand) (domain.User, error) {
	ret := _mock.Called(ctx, userID, command)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, users_service.UpdateProfileCommand) (domain.User, error)); ok {
		return returnFunc(ctx, userID, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, users_service.UpdateProfileCommand) domain.User); ok {
		r0 = returnFunc(ctx, userID, command)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, users_service.UpdateProfileCommand) error); ok {
		r1 = returnFunc(ctx, userID, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUsersService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - command users_service.UpdateProfileCommand
func (_e *MockUsersService_Expecter) UpdateProfile(ctx any, userID any, command any) *MockUsersService_UpdateProfile_Call {
	return &MockUsersService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, command)}
}

func (_c *MockUsersService_UpdateProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID, command users_service.UpdateProfileCommand)) *MockUsersService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 users_service.UpdateProfileCommand
		if args[2] != nil {
			arg2 = args[2].(users_service.UpdateProfileCommand)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersService_UpdateProfile_Call) Return(user domain.User, err error) *MockUsersService_UpdateProfile_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersService_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, command users_service.UpdateProfileCommand) (domain.User, error)) *MockUsersService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCookieManager creates a new instance of MockCookieManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCookieManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCookieManager {
	mock := &MockCookieManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCookieManager is an autogenerated mock type for the CookieManager type
type MockCookieManager struct {
	mock.Mock
}

type MockCookieManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCookieManager) EXPECT() *MockCookieManager_Expecter {
	return &MockCookieManager_Expecter{mock: &_m.Mock}
}

// ClearRefreshToken provides a mock function for the type MockCookieManager
func (_mock *MockCookieManager) ClearRefreshToken(w http.ResponseWriter) {
	_mock.Called(w)
	return
}

// MockCookieManager_ClearRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearRefreshToken'
type MockCookieManager_ClearRefreshToken_Call struct {
	*mock.Call
}

// ClearRefreshToken is a helper method to define mock.On call
//   - w http.ResponseWriter
func (_e *MockCookieManager_Expecter) ClearRefreshToken(w any) *MockCookieManager_ClearRefreshToken_Call {
	return &MockCookieManager_ClearRefreshToken_Call{Call: _e.mock.On("ClearRefreshToken", w)}
}

func (_c *MockCookieManager_ClearRefreshToken_Call) Run(run func(w http.ResponseWriter)) *MockCookieManager_ClearRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCookieManager_ClearRefreshToken_Call) Return() *MockCookieManager_ClearRefreshToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCookieManager_ClearRefreshToken_Call) RunAndReturn(run func(w http.ResponseWriter)) *MockCookieManager_ClearRefreshToken_Call {
	_c.Run(run)
	return _c
}
