// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messages_service

import (
	"context"
	"github.com/wrzdx/Nero/internal/core/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessagesRepository creates a new instance of MockMessagesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessagesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessagesRepository {
	mock := &MockMessagesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessagesRepository is an autogenerated mock type for the MessagesRepository type
type MockMessagesRepository struct {
	mock.Mock
}

type MockMessagesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessagesRepository) EXPECT() *MockMessagesRepository_Expecter {
	return &MockMessagesRepository_Expecter{mock: &_m.Mock}
}

// AppendMessage provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) AppendMessage(ctx context.Context, message domain.Message) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for AppendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Message) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessagesRepository_AppendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendMessage'
type MockMessagesRepository_AppendMessage_Call struct {
	*mock.Call
}

// AppendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message domain.Message
func (_e *MockMessagesRepository_Expecter) AppendMessage(ctx any, message any) *MockMessagesRepository_AppendMessage_Call {
	return &MockMessagesRepository_AppendMessage_Call{Call: _e.mock.On("AppendMessage", ctx, message)}
}

func (_c *MockMessagesRepository_AppendMessage_Call) Run(run func(ctx context.Context, message domain.Message)) *MockMessagesRepository_AppendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Message
		if args[1] != nil {
			arg1 = args[1].(domain.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_AppendMessage_Call) Return(err error) *MockMessagesRepository_AppendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessagesRepository_AppendMessage_Call) RunAndReturn(run func(ctx context.Context, message domain.Message) error) *MockMessagesRepository_AppendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CheckParticipant provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) CheckParticipant(ctx context.Context, chatID uuid.UUID, participantID uuid.UUID) error {
	ret := _mock.Called(ctx, chatID, participantID)

	if len(ret) == 0 {
		panic("no return value specified for CheckParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, chatID, participantID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessagesRepository_CheckParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckParticipant'
type MockMessagesRepository_CheckParticipant_Call struct {
	*mock.Call
}

// CheckParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - participantID uuid.UUID
func (_e *MockMessagesRepository_Expecter) CheckParticipant(ctx any, chatID any, participantID any) *MockMessagesRepository_CheckParticipant_Call {
	return &MockMessagesRepository_CheckParticipant_Call{Call: _e.mock.On("CheckParticipant", ctx, chatID, participantID)}
}

func (_c *MockMessagesRepository_CheckParticipant_Call) Run(run func(ctx context.Context, chatID uuid.UUID, participantID uuid.UUID)) *MockMessagesRepository_CheckParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_CheckParticipant_Call) Return(err error) *MockMessagesRepository_CheckParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessagesRepository_CheckParticipant_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, participantID uuid.UUID) error) *MockMessagesRepository_CheckParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessage provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) DeleteMessage(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessagesRepository_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockMessagesRepository_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMessagesRepository_Expecter) DeleteMessage(ctx any, id any) *MockMessagesRepository_DeleteMessage_Call {
	return &MockMessagesRepository_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", ctx, id)}
}

func (_c *MockMessagesRepository_DeleteMessage_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMessagesRepository_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_DeleteMessage_Call) Return(err error) *MockMessagesRepository_DeleteMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessagesRepository_DeleteMessage_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockMessagesRepository_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) GetMessage(ctx context.Context, id uuid.UUID) (domain.Message, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Message, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Message); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessagesRepository_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type MockMessagesRepository_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMessagesRepository_Expecter) GetMessage(ctx any, id any) *MockMessagesRepository_GetMessage_Call {
	return &MockMessagesRepository_GetMessage_Call{Call: _e.mock.On("GetMessage", ctx, id)}
}

func (_c *MockMessagesRepository_GetMessage_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMessagesRepository_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_GetMessage_Call) Return(message domain.Message, err error) *MockMessagesRepository_GetMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockMessagesRepository_GetMessage_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Message, error)) *MockMessagesRepository_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageByClientID provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) GetMessageByClientID(ctx context.Context, senderID uuid.UUID, clientMessageID uuid.UUID) (domain.Message, error) {
	ret := _mock.Called(ctx, senderID, clientMessageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageByClientID")
	}

	var r0 domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.Message, error)); ok {
		return returnFunc(ctx, senderID, clientMessageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.Message); ok {
		r0 = returnFunc(ctx, senderID, clientMessageID)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, senderID, clientMessageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessagesRepository_GetMessageByClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageByClientID'
type MockMessagesRepository_GetMessageByClientID_Call struct {
	*mock.Call
}

// GetMessageByClientID is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID uuid.UUID
//   - clientMessageID uuid.UUID
func (_e *MockMessagesRepository_Expecter) GetMessageByClientID(ctx any, senderID any, clientMessageID any) *MockMessagesRepository_GetMessageByClientID_Call {
	return &MockMessagesRepository_GetMessageByClientID_Call{Call: _e.mock.On("GetMessageByClientID", ctx, senderID, clientMessageID)}
}

func (_c *MockMessagesRepository_GetMessageByClientID_Call) Run(run func(ctx context.Context, senderID uuid.UUID, clientMessageID uuid.UUID)) *MockMessagesRepository_GetMessageByClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_GetMessageByClientID_Call) Return(message domain.Message, err error) *MockMessagesRepository_GetMessageByClientID_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockMessagesRepository_GetMessageByClientID_Call) RunAndReturn(run func(ctx context.Context, senderID uuid.UUID, clientMessageID uuid.UUID) (domain.Message, error)) *MockMessagesRepository_GetMessageByClientID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) GetMessages(ctx context.Context, chatID uuid.UUID, before *MessageCursor, limit int, after bool) ([]domain.Message, error) {
	ret := _mock.Called(ctx, chatID, before, limit, after)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *MessageCursor, int, bool) ([]domain.Message, error)); ok {
		return returnFunc(ctx, chatID, before, limit, after)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *MessageCursor, int, bool) []domain.Message); ok {
		r0 = returnFunc(ctx, chatID, before, limit, after)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *MessageCursor, int, bool) error); ok {
		r1 = returnFunc(ctx, chatID, before, limit, after)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessagesRepository_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockMessagesRepository_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - before *MessageCursor
//   - limit int
//   - after bool
func (_e *MockMessagesRepository_Expecter) GetMessages(ctx any, chatID any, before any, limit any, after any) *MockMessagesRepository_GetMessages_Call {
	return &MockMessagesRepository_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, chatID, before, limit, after)}
}

func (_c *MockMessagesRepository_GetMessages_Call) Run(run func(ctx context.Context, chatID uuid.UUID, before *MessageCursor, limit int, after bool)) *MockMessagesRepository_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *MessageCursor
		if args[2] != nil {
			arg2 = args[2].(*MessageCursor)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_GetMessages_Call) Return(messages []domain.Message, err error) *MockMessagesRepository_GetMessages_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessagesRepository_GetMessages_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, before *MessageCursor, limit int, after bool) ([]domain.Message, error)) *MockMessagesRepository_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsRead provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) MarkAsRead(ctx context.Context, chatID uuid.UUID, userID uuid.UUID, messageID uuid.UUID) error {
	ret := _mock.Called(ctx, chatID, userID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, chatID, userID, messageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessagesRepository_MarkAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsRead'
type MockMessagesRepository_MarkAsRead_Call struct {
	*mock.Call
}

// MarkAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - userID uuid.UUID
//   - messageID uuid.UUID
func (_e *MockMessagesRepository_Expecter) MarkAsRead(ctx any, chatID any, userID any, messageID any) *MockMessagesRepository_MarkAsRead_Call {
	return &MockMessagesRepository_MarkAsRead_Call{Call: _e.mock.On("MarkAsRead", ctx, chatID, userID, messageID)}
}

func (_c *MockMessagesRepository_MarkAsRead_Call) Run(run func(ctx context.Context, chatID uuid.UUID, userID uuid.UUID, messageID uuid.UUID)) *MockMessagesRepository_MarkAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_MarkAsRead_Call) Return(err error) *MockMessagesRepository_MarkAsRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessagesRepository_MarkAsRead_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, userID uuid.UUID, messageID uuid.UUID) error) *MockMessagesRepository_MarkAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMessage provides a mock function for the type MockMessagesRepository
func (_mock *MockMessagesRepository) UpdateMessage(ctx context.Context, updated domain.Message) error {
	ret := _mock.Called(ctx, updated)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Message) error); ok {
		r0 = returnFunc(ctx, updated)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessagesRepository_UpdateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMessage'
type MockMessagesRepository_UpdateMessage_Call struct {
	*mock.Call
}

// UpdateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - updated domain.Message
func (_e *MockMessagesRepository_Expecter) UpdateMessage(ctx any, updated any) *MockMessagesRepository_UpdateMessage_Call {
	return &MockMessagesRepository_UpdateMessage_Call{Call: _e.mock.On("UpdateMessage", ctx, updated)}
}

func (_c *MockMessagesRepository_UpdateMessage_Call) Run(run func(ctx context.Context, updated domain.Message)) *MockMessagesRepository_UpdateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Message
		if args[1] != nil {
			arg1 = args[1].(domain.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagesRepository_UpdateMessage_Call) Return(err error) *MockMessagesRepository_UpdateMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessagesRepository_UpdateMessage_Call) RunAndReturn(run func(ctx context.Context, updated domain.Message) error) *MockMessagesRepository_UpdateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatsRepository creates a new instance of MockChatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatsRepository {
	mock := &MockChatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatsRepository is an autogenerated mock type for the ChatsRepository type
type MockChatsRepository struct {
	mock.Mock
}

type MockChatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatsRepository) EXPECT() *MockChatsRepository_Expecter {
	return &MockChatsRepository_Expecter{mock: &_m.Mock}
}

// GetChatForUpdate provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) GetChatForUpdate(ctx context.Context, chatID uuid.UUID) (domain.Chat, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetChatForUpdate")
	}

	var r0 domain.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Chat, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Chat); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Get(0).(domain.Chat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_GetChatForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatForUpdate'
type MockChatsRepository_GetChatForUpdate_Call struct {
	*mock.Call
}

// GetChatForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
func (_e *MockChatsRepository_Expecter) GetChatForUpdate(ctx any, chatID any) *MockChatsRepository_GetChatForUpdate_Call {
	return &MockChatsRepository_GetChatForUpdate_Call{Call: _e.mock.On("GetChatForUpdate", ctx, chatID)}
}

func (_c *MockChatsRepository_GetChatForUpdate_Call) Run(run func(ctx context.Context, chatID uuid.UUID)) *MockChatsRepository_GetChatForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatsRepository_GetChatForUpdate_Call) Return(chat domain.Chat, err error) *MockChatsRepository_GetChatForUpdate_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockChatsRepository_GetChatForUpdate_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID) (domain.Chat, error)) *MockChatsRepository_GetChatForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetDirectMessageState provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) GetDirectMessageState(ctx context.Context, chatID uuid.UUID) (DirectMessageState, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetDirectMessageState")
	}

	var r0 DirectMessageState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (DirectMessageState, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) DirectMessageState); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Get(0).(DirectMessageState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_GetDirectMessageState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDirectMessageState'
type MockChatsRepository_GetDirectMessageState_Call struct {
	*mock.Call
}

// GetDirectMessageState is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
func (_e *MockChatsRepository_Expecter) GetDirectMessageState(ctx any, chatID any) *MockChatsRepository_GetDirectMessageState_Call {
	return &MockChatsRepository_GetDirectMessageState_Call{Call: _e.mock.On("GetDirectMessageState", ctx, chatID)}
}

func (_c *MockChatsRepository_GetDirectMessageState_Call) Run(run func(ctx context.Context, chatID uuid.UUID)) *MockChatsRepository_GetDirectMessageState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatsRepository_GetDirectMessageState_Call) Return(directMessageState DirectMessageState, err error) *MockChatsRepository_GetDirectMessageState_Call {
	_c.Call.Return(directMessageState, err)
	return _c
}

func (_c *MockChatsRepository_GetDirectMessageState_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID) (DirectMessageState, error)) *MockChatsRepository_GetDirectMessageState_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupSenderState provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) GetGroupSenderState(ctx context.Context, chatID uuid.UUID, senderID uuid.UUID) (AccountState, error) {
	ret := _mock.Called(ctx, chatID, senderID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupSenderState")
	}

	var r0 AccountState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (AccountState, error)); ok {
		return returnFunc(ctx, chatID, senderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) AccountState); ok {
		r0 = returnFunc(ctx, chatID, senderID)
	} else {
		r0 = ret.Get(0).(AccountState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, chatID, senderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsRepository_GetGroupSenderState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupSenderState'
type MockChatsRepository_GetGroupSenderState_Call struct {
	*mock.Call
}

// GetGroupSenderState is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - senderID uuid.UUID
func (_e *MockChatsRepository_Expecter) GetGroupSenderState(ctx any, chatID any, senderID any) *MockChatsRepository_GetGroupSenderState_Call {
	return &MockChatsRepository_GetGroupSenderState_Call{Call: _e.mock.On("GetGroupSenderState", ctx, chatID, senderID)}
}

func (_c *MockChatsRepository_GetGroupSenderState_Call) Run(run func(ctx context.Context, chatID uuid.UUID, senderID uuid.UUID)) *MockChatsRepository_GetGroupSenderState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsRepository_GetGroupSenderState_Call) Return(accountState AccountState, err error) *MockChatsRepository_GetGroupSenderState_Call {
	_c.Call.Return(accountState, err)
	return _c
}

func (_c *MockChatsRepository_GetGroupSenderState_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, senderID uuid.UUID) (AccountState, error)) *MockChatsRepository_GetGroupSenderState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateChatLastMsgID provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) UpdateChatLastMsgID(ctx context.Context, chatID uuid.UUID, newLastMessageID *uuid.UUID) error {
	ret := _mock.Called(ctx, chatID, newLastMessageID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChatLastMsgID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, chatID, newLastMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatsRepository_UpdateChatLastMsgID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateChatLastMsgID'
type MockChatsRepository_UpdateChatLastMsgID_Call struct {
	*mock.Call
}

// UpdateChatLastMsgID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - newLastMessageID *uuid.UUID
func (_e *MockChatsRepository_Expecter) UpdateChatLastMsgID(ctx any, chatID any, newLastMessageID any) *MockChatsRepository_UpdateChatLastMsgID_Call {
	return &MockChatsRepository_UpdateChatLastMsgID_Call{Call: _e.mock.On("UpdateChatLastMsgID", ctx, chatID, newLastMessageID)}
}

func (_c *MockChatsRepository_UpdateChatLastMsgID_Call) Run(run func(ctx context.Context, chatID uuid.UUID, newLastMessageID *uuid.UUID)) *MockChatsRepository_UpdateChatLastMsgID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsRepository_UpdateChatLastMsgID_Call) Return(err error) *MockChatsRepository_UpdateChatLastMsgID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatsRepository_UpdateChatLastMsgID_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, newLastMessageID *uuid.UUID) error) *MockChatsRepository_UpdateChatLastMsgID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastReadMessages provides a mock function for the type MockChatsRepository
func (_mock *MockChatsRepository) UpdateLastReadMessages(ctx context.Context, chatID uuid.UUID, oldMessageID uuid.UUID, newMessageID *uuid.UUID) error {
	ret := _mock.Called(ctx, chatID, oldMessageID, newMessageID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastReadMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, chatID, oldMessageID, newMessageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatsRepository_UpdateLastReadMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastReadMessages'
type MockChatsRepository_UpdateLastReadMessages_Call struct {
	*mock.Call
}

// UpdateLastReadMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - oldMessageID uuid.UUID
//   - newMessageID *uuid.UUID
func (_e *MockChatsRepository_Expecter) UpdateLastReadMessages(ctx any, chatID any, oldMessageID any, newMessageID any) *MockChatsRepository_UpdateLastReadMessages_Call {
	return &MockChatsRepository_UpdateLastReadMessages_Call{Call: _e.mock.On("UpdateLastReadMessages", ctx, chatID, oldMessageID, newMessageID)}
}

func (_c *MockChatsRepository_UpdateLastReadMessages_Call) Run(run func(ctx context.Context, chatID uuid.UUID, oldMessageID uuid.UUID, newMessageID *uuid.UUID)) *MockChatsRepository_UpdateLastReadMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockChatsRepository_UpdateLastReadMessages_Call) Return(err error) *MockChatsRepository_UpdateLastReadMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatsRepository_UpdateLastReadMessages_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, oldMessageID uuid.UUID, newMessageID *uuid.UUID) error) *MockChatsRepository_UpdateLastReadMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTXManager creates a new instance of MockTXManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTXManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTXManager {
	mock := &MockTXManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTXManager is an autogenerated mock type for the TXManager type
type MockTXManager struct {
	mock.Mock
}

type MockTXManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTXManager) EXPECT() *MockTXManager_Expecter {
	return &MockTXManager_Expecter{mock: &_m.Mock}
}

// WithinTransaction provides a mock function for the type MockTXManager
func (_mock *MockTXManager) WithinTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTXManager_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockTXManager_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTXManager_Expecter) WithinTransaction(ctx any, fn any) *MockTXManager_WithinTransaction_Call {
	return &MockTXManager_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, fn)}
}

func (_c *MockTXManager_WithinTransaction_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTXManager_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) Return(err error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// MessageCreated provides a mock function for the type MockNotifier
func (_mock *MockNotifier) MessageCreated(ctx context.Context, message domain.Message) {
	_mock.Called(ctx, message)
	return
}

// MockNotifier_MessageCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageCreated'
type MockNotifier_MessageCreated_Call struct {
	*mock.Call
}

// MessageCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - message domain.Message
func (_e *MockNotifier_Expecter) MessageCreated(ctx any, message any) *MockNotifier_MessageCreated_Call {
	return &MockNotifier_MessageCreated_Call{Call: _e.mock.On("MessageCreated", ctx, message)}
}

func (_c *MockNotifier_MessageCreated_Call) Run(run func(ctx context.Context, message domain.Message)) *MockNotifier_MessageCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Message
		if args[1] != nil {
			arg1 = args[1].(domain.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifier_MessageCreated_Call) Return() *MockNotifier_MessageCreated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_MessageCreated_Call) RunAndReturn(run func(ctx context.Context, message domain.Message)) *MockNotifier_MessageCreated_Call {
	_c.Run(run)
	return _c
}

// MessageDeleted provides a mock function for the type MockNotifier
func (_mock *MockNotifier) MessageDeleted(ctx context.Context, chatID uuid.UUID, messageID uuid.UUID) {
	_mock.Called(ctx, chatID, messageID)
	return
}

// MockNotifier_MessageDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageDeleted'
type MockNotifier_MessageDeleted_Call struct {
	*mock.Call
}

// MessageDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
//   - messageID uuid.UUID
func (_e *MockNotifier_Expecter) MessageDeleted(ctx any, chatID any, messageID any) *MockNotifier_MessageDeleted_Call {
	return &MockNotifier_MessageDeleted_Call{Call: _e.mock.On("MessageDeleted", ctx, chatID, messageID)}
}

func (_c *MockNotifier_MessageDeleted_Call) Run(run func(ctx context.Context, chatID uuid.UUID, messageID uuid.UUID)) *MockNotifier_MessageDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotifier_MessageDeleted_Call) Return() *MockNotifier_MessageDeleted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_MessageDeleted_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID, messageID uuid.UUID)) *MockNotifier_MessageDeleted_Call {
	_c.Run(run)
	return _c
}

// MessageEdited provides a mock function for the type MockNotifier
func (_mock *MockNotifier) MessageEdited(ctx context.Context, message domain.Message) {
	_mock.Called(ctx, message)
	return
}

// MockNotifier_MessageEdited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageEdited'
type MockNotifier_MessageEdited_Call struct {
	*mock.Call
}

// MessageEdited is a helper method to define mock.On call
//   - ctx context.Context
//   - message domain.Message
func (_e *MockNotifier_Expecter) MessageEdited(ctx any, message any) *MockNotifier_MessageEdited_Call {
	return &MockNotifier_MessageEdited_Call{Call: _e.mock.On("MessageEdited", ctx, message)}
}

func (_c *MockNotifier_MessageEdited_Call) Run(run func(ctx context.Context, message domain.Message)) *MockNotifier_MessageEdited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Message
		if args[1] != nil {
			arg1 = args[1].(domain.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifier_MessageEdited_Call) Return() *MockNotifier_MessageEdited_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_MessageEdited_Call) RunAndReturn(run func(ctx context.Context, message domain.Message)) *MockNotifier_MessageEdited_Call {
	_c.Run(run)
	return _c
}
