// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package users_service

import (
	"context"
	"github.com/wrzdx/Nero/internal/core/domain"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// DeleteUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) DeleteUser(ctx context.Context, id uuid.UUID, profile domain.UserProfile, deletedAt time.Time) error {
	ret := _mock.Called(ctx, id, profile, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.UserProfile, time.Time) error); ok {
		r0 = returnFunc(ctx, id, profile, deletedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUsersRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - profile domain.UserProfile
//   - deletedAt time.Time
func (_e *MockUsersRepository_Expecter) DeleteUser(ctx any, id any, profile any, deletedAt any) *MockUsersRepository_DeleteUser_Call {
	return &MockUsersRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id, profile, deletedAt)}
}

func (_c *MockUsersRepository_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID, profile domain.UserProfile, deletedAt time.Time)) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.UserProfile
		if args[2] != nil {
			arg2 = args[2].(domain.UserProfile)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersRepository_DeleteUser_Call) Return(err error) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, profile domain.UserProfile, deletedAt time.Time) error) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUser(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUsersRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsersRepository_Expecter) GetUser(ctx any, id any) *MockUsersRepository_GetUser_Call {
	return &MockUsersRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUsersRepository_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUser_Call) Return(user domain.User, err error) *MockUsersRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.User, error)) *MockUsersRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserForUpdate provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserForUpdate(ctx context.Context, userID uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserForUpdate")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserForUpdate'
type MockUsersRepository_GetUserForUpdate_Call struct {
	*mock.Call
}

// GetUserForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUsersRepository_Expecter) GetUserForUpdate(ctx any, userID any) *MockUsersRepository_GetUserForUpdate_Call {
	return &MockUsersRepository_GetUserForUpdate_Call{Call: _e.mock.On("GetUserForUpdate", ctx, userID)}
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) Return(user domain.User, err error) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserForUpdate_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (domain.User, error)) *MockUsersRepository_GetUserForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) SearchUsers(ctx context.Context, requesterID uuid.UUID, prefix string, limit int) ([]UserSearchResult, error) {
	ret := _mock.Called(ctx, requesterID, prefix, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []UserSearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) ([]UserSearchResult, error)); ok {
		return returnFunc(ctx, requesterID, prefix, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) []UserSearchResult); ok {
		r0 = returnFunc(ctx, requesterID, prefix, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]UserSearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int) error); ok {
		r1 = returnFunc(ctx, requesterID, prefix, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockUsersRepository_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - requesterID uuid.UUID
//   - prefix string
//   - limit int
func (_e *MockUsersRepository_Expecter) SearchUsers(ctx any, requesterID any, prefix any, limit any) *MockUsersRepository_SearchUsers_Call {
	return &MockUsersRepository_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, requesterID, prefix, limit)}
}

func (_c *MockUsersRepository_SearchUsers_Call) Run(run func(ctx context.Context, requesterID uuid.UUID, prefix string, limit int)) *MockUsersRepository_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersRepository_SearchUsers_Call) Return(userSearchResults []UserSearchResult, err error) *MockUsersRepository_SearchUsers_Call {
	_c.Call.Return(userSearchResults, err)
	return _c
}

func (_c *MockUsersRepository_SearchUsers_Call) RunAndReturn(run func(ctx context.Context, requesterID uuid.UUID, prefix string, limit int) ([]UserSearchResult, error)) *MockUsersRepository_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserProfile provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) UpdateUserProfile(ctx context.Context, id uuid.UUID, profile domain.UserProfile) error {
	ret := _mock.Called(ctx, id, profile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.UserProfile) error); ok {
		r0 = returnFunc(ctx, id, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_UpdateUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserProfile'
type MockUsersRepository_UpdateUserProfile_Call struct {
	*mock.Call
}

// UpdateUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - profile domain.UserProfile
func (_e *MockUsersRepository_Expecter) UpdateUserProfile(ctx any, id any, profile any) *MockUsersRepository_UpdateUserProfile_Call {
	return &MockUsersRepository_UpdateUserProfile_Call{Call: _e.mock.On("UpdateUserProfile", ctx, id, profile)}
}

func (_c *MockUsersRepository_UpdateUserProfile_Call) Run(run func(ctx context.Context, id uuid.UUID, profile domain.UserProfile)) *MockUsersRepository_UpdateUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.UserProfile
		if args[2] != nil {
			arg2 = args[2].(domain.UserProfile)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_UpdateUserProfile_Call) Return(err error) *MockUsersRepository_UpdateUserProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_UpdateUserProfile_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, profile domain.UserProfile) error) *MockUsersRepository_UpdateUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionsRepository creates a new instance of MockSessionsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionsRepository {
	mock := &MockSessionsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionsRepository is an autogenerated mock type for the SessionsRepository type
type MockSessionsRepository struct {
	mock.Mock
}

type MockSessionsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionsRepository) EXPECT() *MockSessionsRepository_Expecter {
	return &MockSessionsRepository_Expecter{mock: &_m.Mock}
}

// DeleteAllSessions provides a mock function for the type MockSessionsRepository
func (_mock *MockSessionsRepository) DeleteAllSessions(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionsRepository_DeleteAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllSessions'
type MockSessionsRepository_DeleteAllSessions_Call struct {
	*mock.Call
}

// DeleteAllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSessionsRepository_Expecter) DeleteAllSessions(ctx any, userID any) *MockSessionsRepository_DeleteAllSessions_Call {
	return &MockSessionsRepository_DeleteAllSessions_Call{Call: _e.mock.On("DeleteAllSessions", ctx, userID)}
}

func (_c *MockSessionsRepository_DeleteAllSessions_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSessionsRepository_DeleteAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionsRepository_DeleteAllSessions_Call) Return(err error) *MockSessionsRepository_DeleteAllSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionsRepository_DeleteAllSessions_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockSessionsRepository_DeleteAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTXManager creates a new instance of MockTXManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTXManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTXManager {
	mock := &MockTXManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTXManager is an autogenerated mock type for the TXManager type
type MockTXManager struct {
	mock.Mock
}

type MockTXManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTXManager) EXPECT() *MockTXManager_Expecter {
	return &MockTXManager_Expecter{mock: &_m.Mock}
}

// WithinTransaction provides a mock function for the type MockTXManager
func (_mock *MockTXManager) WithinTransaction(ctx context.Context, fn func(context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTXManager_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockTXManager_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *MockTXManager_Expecter) WithinTransaction(ctx any, fn any) *MockTXManager_WithinTransaction_Call {
	return &MockTXManager_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, fn)}
}

func (_c *MockTXManager_WithinTransaction_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *MockTXManager_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) Return(err error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTXManager_WithinTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(context.Context) error) error) *MockTXManager_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}
