// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chats_transport_http

import (
	"context"
	"github.com/wrzdx/Nero/internal/core/domain"
	"github.com/wrzdx/Nero/internal/features/chats/service"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatsService creates a new instance of MockChatsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatsService {
	mock := &MockChatsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatsService is an autogenerated mock type for the ChatsService type
type MockChatsService struct {
	mock.Mock
}

type MockChatsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatsService) EXPECT() *MockChatsService_Expecter {
	return &MockChatsService_Expecter{mock: &_m.Mock}
}

// AddGroupParticipantsByUsernames provides a mock function for the type MockChatsService
func (_mock *MockChatsService) AddGroupParticipantsByUsernames(ctx context.Context, command chats_service.AddGroupParticipantsByUsernamesCommand) ([]chats_service.UsernameParticipantResult, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for AddGroupParticipantsByUsernames")
	}

	var r0 []chats_service.UsernameParticipantResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chats_service.AddGroupParticipantsByUsernamesCommand) ([]chats_service.UsernameParticipantResult, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, chats_service.AddGroupParticipantsByUsernamesCommand) []chats_service.UsernameParticipantResult); ok {
		r0 = returnFunc(ctx, command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chats_service.UsernameParticipantResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, chats_service.AddGroupParticipantsByUsernamesCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsService_AddGroupParticipantsByUsernames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGroupParticipantsByUsernames'
type MockChatsService_AddGroupParticipantsByUsernames_Call struct {
	*mock.Call
}

// AddGroupParticipantsByUsernames is a helper method to define mock.On call
//   - ctx context.Context
//   - command chats_service.AddGroupParticipantsByUsernamesCommand
func (_e *MockChatsService_Expecter) AddGroupParticipantsByUsernames(ctx any, command any) *MockChatsService_AddGroupParticipantsByUsernames_Call {
	return &MockChatsService_AddGroupParticipantsByUsernames_Call{Call: _e.mock.On("AddGroupParticipantsByUsernames", ctx, command)}
}

func (_c *MockChatsService_AddGroupParticipantsByUsernames_Call) Run(run func(ctx context.Context, command chats_service.AddGroupParticipantsByUsernamesCommand)) *MockChatsService_AddGroupParticipantsByUsernames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chats_service.AddGroupParticipantsByUsernamesCommand
		if args[1] != nil {
			arg1 = args[1].(chats_service.AddGroupParticipantsByUsernamesCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatsService_AddGroupParticipantsByUsernames_Call) Return(usernameParticipantResults []chats_service.UsernameParticipantResult, err error) *MockChatsService_AddGroupParticipantsByUsernames_Call {
	_c.Call.Return(usernameParticipantResults, err)
	return _c
}

func (_c *MockChatsService_AddGroupParticipantsByUsernames_Call) RunAndReturn(run func(ctx context.Context, command chats_service.AddGroupParticipantsByUsernamesCommand) ([]chats_service.UsernameParticipantResult, error)) *MockChatsService_AddGroupParticipantsByUsernames_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDirectByUsername provides a mock function for the type MockChatsService
func (_mock *MockChatsService) CreateDirectByUsername(ctx context.Context, currentUserID uuid.UUID, peerUsername string) (domain.DirectChat, bool, error) {
	ret := _mock.Called(ctx, currentUserID, peerUsername)

	if len(ret) == 0 {
		panic("no return value specified for CreateDirectByUsername")
	}

	var r0 domain.DirectChat
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (domain.DirectChat, bool, error)); ok {
		return returnFunc(ctx, currentUserID, peerUsername)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) domain.DirectChat); ok {
		r0 = returnFunc(ctx, currentUserID, peerUsername)
	} else {
		r0 = ret.Get(0).(domain.DirectChat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) bool); ok {
		r1 = returnFunc(ctx, currentUserID, peerUsername)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, string) error); ok {
		r2 = returnFunc(ctx, currentUserID, peerUsername)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockChatsService_CreateDirectByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDirectByUsername'
type MockChatsService_CreateDirectByUsername_Call struct {
	*mock.Call
}

// CreateDirectByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - currentUserID uuid.UUID
//   - peerUsername string
func (_e *MockChatsService_Expecter) CreateDirectByUsername(ctx any, currentUserID any, peerUsername any) *MockChatsService_CreateDirectByUsername_Call {
	return &MockChatsService_CreateDirectByUsername_Call{Call: _e.mock.On("CreateDirectByUsername", ctx, currentUserID, peerUsername)}
}

func (_c *MockChatsService_CreateDirectByUsername_Call) Run(run func(ctx context.Context, currentUserID uuid.UUID, peerUsername string)) *MockChatsService_CreateDirectByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsService_CreateDirectByUsername_Call) Return(directChat domain.DirectChat, b bool, err error) *MockChatsService_CreateDirectByUsername_Call {
	_c.Call.Return(directChat, b, err)
	return _c
}

func (_c *MockChatsService_CreateDirectByUsername_Call) RunAndReturn(run func(ctx context.Context, currentUserID uuid.UUID, peerUsername string) (domain.DirectChat, bool, error)) *MockChatsService_CreateDirectByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroupByUsernames provides a mock function for the type MockChatsService
func (_mock *MockChatsService) CreateGroupByUsernames(ctx context.Context, creatorID uuid.UUID, command chats_service.CreateGroupByUsernamesCommand) (domain.GroupChat, error) {
	ret := _mock.Called(ctx, creatorID, command)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupByUsernames")
	}

	var r0 domain.GroupChat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, chats_service.CreateGroupByUsernamesCommand) (domain.GroupChat, error)); ok {
		return returnFunc(ctx, creatorID, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, chats_service.CreateGroupByUsernamesCommand) domain.GroupChat); ok {
		r0 = returnFunc(ctx, creatorID, command)
	} else {
		r0 = ret.Get(0).(domain.GroupChat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, chats_service.CreateGroupByUsernamesCommand) error); ok {
		r1 = returnFunc(ctx, creatorID, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsService_CreateGroupByUsernames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupByUsernames'
type MockChatsService_CreateGroupByUsernames_Call struct {
	*mock.Call
}

// CreateGroupByUsernames is a helper method to define mock.On call
//   - ctx context.Context
//   - creatorID uuid.UUID
//   - command chats_service.CreateGroupByUsernamesCommand
func (_e *MockChatsService_Expecter) CreateGroupByUsernames(ctx any, creatorID any, command any) *MockChatsService_CreateGroupByUsernames_Call {
	return &MockChatsService_CreateGroupByUsernames_Call{Call: _e.mock.On("CreateGroupByUsernames", ctx, creatorID, command)}
}

func (_c *MockChatsService_CreateGroupByUsernames_Call) Run(run func(ctx context.Context, creatorID uuid.UUID, command chats_service.CreateGroupByUsernamesCommand)) *MockChatsService_CreateGroupByUsernames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 chats_service.CreateGroupByUsernamesCommand
		if args[2] != nil {
			arg2 = args[2].(chats_service.CreateGroupByUsernamesCommand)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsService_CreateGroupByUsernames_Call) Return(groupChat domain.GroupChat, err error) *MockChatsService_CreateGroupByUsernames_Call {
	_c.Call.Return(groupChat, err)
	return _c
}

func (_c *MockChatsService_CreateGroupByUsernames_Call) RunAndReturn(run func(ctx context.Context, creatorID uuid.UUID, command chats_service.CreateGroupByUsernamesCommand) (domain.GroupChat, error)) *MockChatsService_CreateGroupByUsernames_Call {
	_c.Call.Return(run)
	return _c
}

// ListChats provides a mock function for the type MockChatsService
func (_mock *MockChatsService) ListChats(ctx context.Context, requesterID uuid.UUID, query chats_service.ListChatsQuery) (chats_service.ChatPage, error) {
	ret := _mock.Called(ctx, requesterID, query)

	if len(ret) == 0 {
		panic("no return value specified for ListChats")
	}

	var r0 chats_service.ChatPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, chats_service.ListChatsQuery) (chats_service.ChatPage, error)); ok {
		return returnFunc(ctx, requesterID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, chats_service.ListChatsQuery) chats_service.ChatPage); ok {
		r0 = returnFunc(ctx, requesterID, query)
	} else {
		r0 = ret.Get(0).(chats_service.ChatPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, chats_service.ListChatsQuery) error); ok {
		r1 = returnFunc(ctx, requesterID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsService_ListChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListChats'
type MockChatsService_ListChats_Call struct {
	*mock.Call
}

// ListChats is a helper method to define mock.On call
//   - ctx context.Context
//   - requesterID uuid.UUID
//   - query chats_service.ListChatsQuery
func (_e *MockChatsService_Expecter) ListChats(ctx any, requesterID any, query any) *MockChatsService_ListChats_Call {
	return &MockChatsService_ListChats_Call{Call: _e.mock.On("ListChats", ctx, requesterID, query)}
}

func (_c *MockChatsService_ListChats_Call) Run(run func(ctx context.Context, requesterID uuid.UUID, query chats_service.ListChatsQuery)) *MockChatsService_ListChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 chats_service.ListChatsQuery
		if args[2] != nil {
			arg2 = args[2].(chats_service.ListChatsQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsService_ListChats_Call) Return(chatPage chats_service.ChatPage, err error) *MockChatsService_ListChats_Call {
	_c.Call.Return(chatPage, err)
	return _c
}

func (_c *MockChatsService_ListChats_Call) RunAndReturn(run func(ctx context.Context, requesterID uuid.UUID, query chats_service.ListChatsQuery) (chats_service.ChatPage, error)) *MockChatsService_ListChats_Call {
	_c.Call.Return(run)
	return _c
}

// ListGroupParticipants provides a mock function for the type MockChatsService
func (_mock *MockChatsService) ListGroupParticipants(ctx context.Context, requesterID uuid.UUID, query chats_service.ListGroupParticipantsQuery) (chats_service.GroupParticipantPage, error) {
	ret := _mock.Called(ctx, requesterID, query)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupParticipants")
	}

	var r0 chats_service.GroupParticipantPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, chats_service.ListGroupParticipantsQuery) (chats_service.GroupParticipantPage, error)); ok {
		return returnFunc(ctx, requesterID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, chats_service.ListGroupParticipantsQuery) chats_service.GroupParticipantPage); ok {
		r0 = returnFunc(ctx, requesterID, query)
	} else {
		r0 = ret.Get(0).(chats_service.GroupParticipantPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, chats_service.ListGroupParticipantsQuery) error); ok {
		r1 = returnFunc(ctx, requesterID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsService_ListGroupParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroupParticipants'
type MockChatsService_ListGroupParticipants_Call struct {
	*mock.Call
}

// ListGroupParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - requesterID uuid.UUID
//   - query chats_service.ListGroupParticipantsQuery
func (_e *MockChatsService_Expecter) ListGroupParticipants(ctx any, requesterID any, query any) *MockChatsService_ListGroupParticipants_Call {
	return &MockChatsService_ListGroupParticipants_Call{Call: _e.mock.On("ListGroupParticipants", ctx, requesterID, query)}
}

func (_c *MockChatsService_ListGroupParticipants_Call) Run(run func(ctx context.Context, requesterID uuid.UUID, query chats_service.ListGroupParticipantsQuery)) *MockChatsService_ListGroupParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 chats_service.ListGroupParticipantsQuery
		if args[2] != nil {
			arg2 = args[2].(chats_service.ListGroupParticipantsQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatsService_ListGroupParticipants_Call) Return(groupParticipantPage chats_service.GroupParticipantPage, err error) *MockChatsService_ListGroupParticipants_Call {
	_c.Call.Return(groupParticipantPage, err)
	return _c
}

func (_c *MockChatsService_ListGroupParticipants_Call) RunAndReturn(run func(ctx context.Context, requesterID uuid.UUID, query chats_service.ListGroupParticipantsQuery) (chats_service.GroupParticipantPage, error)) *MockChatsService_ListGroupParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGroupParticipantByUsername provides a mock function for the type MockChatsService
func (_mock *MockChatsService) RemoveGroupParticipantByUsername(ctx context.Context, command chats_service.RemoveGroupParticipantByUsernameCommand) error {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGroupParticipantByUsername")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chats_service.RemoveGroupParticipantByUsernameCommand) error); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatsService_RemoveGroupParticipantByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGroupParticipantByUsername'
type MockChatsService_RemoveGroupParticipantByUsername_Call struct {
	*mock.Call
}

// RemoveGroupParticipantByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - command chats_service.RemoveGroupParticipantByUsernameCommand
func (_e *MockChatsService_Expecter) RemoveGroupParticipantByUsername(ctx any, command any) *MockChatsService_RemoveGroupParticipantByUsername_Call {
	return &MockChatsService_RemoveGroupParticipantByUsername_Call{Call: _e.mock.On("RemoveGroupParticipantByUsername", ctx, command)}
}

func (_c *MockChatsService_RemoveGroupParticipantByUsername_Call) Run(run func(ctx context.Context, command chats_service.RemoveGroupParticipantByUsernameCommand)) *MockChatsService_RemoveGroupParticipantByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chats_service.RemoveGroupParticipantByUsernameCommand
		if args[1] != nil {
			arg1 = args[1].(chats_service.RemoveGroupParticipantByUsernameCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatsService_RemoveGroupParticipantByUsername_Call) Return(err error) *MockChatsService_RemoveGroupParticipantByUsername_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatsService_RemoveGroupParticipantByUsername_Call) RunAndReturn(run func(ctx context.Context, command chats_service.RemoveGroupParticipantByUsernameCommand) error) *MockChatsService_RemoveGroupParticipantByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function for the type MockChatsService
func (_mock *MockChatsService) UpdateGroup(ctx context.Context, command chats_service.UpdateGroupCommand) (domain.GroupChat, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 domain.GroupChat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chats_service.UpdateGroupCommand) (domain.GroupChat, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, chats_service.UpdateGroupCommand) domain.GroupChat); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(domain.GroupChat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, chats_service.UpdateGroupCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatsService_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockChatsService_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - command chats_service.UpdateGroupCommand
func (_e *MockChatsService_Expecter) UpdateGroup(ctx any, command any) *MockChatsService_UpdateGroup_Call {
	return &MockChatsService_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, command)}
}

func (_c *MockChatsService_UpdateGroup_Call) Run(run func(ctx context.Context, command chats_service.UpdateGroupCommand)) *MockChatsService_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chats_service.UpdateGroupCommand
		if args[1] != nil {
			arg1 = args[1].(chats_service.UpdateGroupCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatsService_UpdateGroup_Call) Return(groupChat domain.GroupChat, err error) *MockChatsService_UpdateGroup_Call {
	_c.Call.Return(groupChat, err)
	return _c
}

func (_c *MockChatsService_UpdateGroup_Call) RunAndReturn(run func(ctx context.Context, command chats_service.UpdateGroupCommand) (domain.GroupChat, error)) *MockChatsService_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}
