// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_transport_http

import (
	"context"
	"github.com/wrzdx/Nero/internal/core/auth"
	"github.com/wrzdx/Nero/internal/core/domain"
	"github.com/wrzdx/Nero/internal/features/auth/service"
	"net/http"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ChangePassword(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string) error {
	ret := _mock.Called(ctx, userID, currentPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, userID, currentPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockAuthService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - currentPassword string
//   - newPassword string
func (_e *MockAuthService_Expecter) ChangePassword(ctx any, userID any, currentPassword any, newPassword any) *MockAuthService_ChangePassword_Call {
	return &MockAuthService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, currentPassword, newPassword)}
}

func (_c *MockAuthService_ChangePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string)) *MockAuthService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthService_ChangePassword_Call) Return(err error) *MockAuthService_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string) error) *MockAuthService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, username string, password string) (auth.TokenPair, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 auth.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (auth.TokenPair, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) auth.TokenPair); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(auth.TokenPair)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx any, username any, password any) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(tokenPair auth.TokenPair, err error) *MockAuthService_Login_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (auth.TokenPair, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Logout(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) Logout(ctx any, refreshToken any) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(err error) *MockAuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Refresh(ctx context.Context, token string) (auth.TokenPair, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 auth.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (auth.TokenPair, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) auth.TokenPair); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(auth.TokenPair)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthService_Expecter) Refresh(ctx any, token any) *MockAuthService_Refresh_Call {
	return &MockAuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, token)}
}

func (_c *MockAuthService_Refresh_Call) Run(run func(ctx context.Context, token string)) *MockAuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Refresh_Call) Return(tokenPair auth.TokenPair, err error) *MockAuthService_Refresh_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthService_Refresh_Call) RunAndReturn(run func(ctx context.Context, token string) (auth.TokenPair, error)) *MockAuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, payload auth_service.RegisterCommand) (domain.User, auth.TokenPair, error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.User
	var r1 auth.TokenPair
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth_service.RegisterCommand) (domain.User, auth.TokenPair, error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth_service.RegisterCommand) domain.User); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth_service.RegisterCommand) auth.TokenPair); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Get(1).(auth.TokenPair)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, auth_service.RegisterCommand) error); ok {
		r2 = returnFunc(ctx, payload)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - payload auth_service.RegisterCommand
func (_e *MockAuthService_Expecter) Register(ctx any, payload any) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, payload)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, payload auth_service.RegisterCommand)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth_service.RegisterCommand
		if args[1] != nil {
			arg1 = args[1].(auth_service.RegisterCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(user domain.User, tokenPair auth.TokenPair, err error) *MockAuthService_Register_Call {
	_c.Call.Return(user, tokenPair, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, payload auth_service.RegisterCommand) (domain.User, auth.TokenPair, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCookieManager creates a new instance of MockCookieManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCookieManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCookieManager {
	mock := &MockCookieManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCookieManager is an autogenerated mock type for the CookieManager type
type MockCookieManager struct {
	mock.Mock
}

type MockCookieManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCookieManager) EXPECT() *MockCookieManager_Expecter {
	return &MockCookieManager_Expecter{mock: &_m.Mock}
}

// ClearRefreshToken provides a mock function for the type MockCookieManager
func (_mock *MockCookieManager) ClearRefreshToken(w http.ResponseWriter) {
	_mock.Called(w)
	return
}

// MockCookieManager_ClearRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearRefreshToken'
type MockCookieManager_ClearRefreshToken_Call struct {
	*mock.Call
}

// ClearRefreshToken is a helper method to define mock.On call
//   - w http.ResponseWriter
func (_e *MockCookieManager_Expecter) ClearRefreshToken(w any) *MockCookieManager_ClearRefreshToken_Call {
	return &MockCookieManager_ClearRefreshToken_Call{Call: _e.mock.On("ClearRefreshToken", w)}
}

func (_c *MockCookieManager_ClearRefreshToken_Call) Run(run func(w http.ResponseWriter)) *MockCookieManager_ClearRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCookieManager_ClearRefreshToken_Call) Return() *MockCookieManager_ClearRefreshToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCookieManager_ClearRefreshToken_Call) RunAndReturn(run func(w http.ResponseWriter)) *MockCookieManager_ClearRefreshToken_Call {
	_c.Run(run)
	return _c
}

// GetRefreshToken provides a mock function for the type MockCookieManager
func (_mock *MockCookieManager) GetRefreshToken(r *http.Request) (string, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (string, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCookieManager_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockCookieManager_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockCookieManager_Expecter) GetRefreshToken(r any) *MockCookieManager_GetRefreshToken_Call {
	return &MockCookieManager_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", r)}
}

func (_c *MockCookieManager_GetRefreshToken_Call) Run(run func(r *http.Request)) *MockCookieManager_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCookieManager_GetRefreshToken_Call) Return(s string, err error) *MockCookieManager_GetRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCookieManager_GetRefreshToken_Call) RunAndReturn(run func(r *http.Request) (string, error)) *MockCookieManager_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SetRefreshToken provides a mock function for the type MockCookieManager
func (_mock *MockCookieManager) SetRefreshToken(w http.ResponseWriter, token string) {
	_mock.Called(w, token)
	return
}

// MockCookieManager_SetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRefreshToken'
type MockCookieManager_SetRefreshToken_Call struct {
	*mock.Call
}

// SetRefreshToken is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - token string
func (_e *MockCookieManager_Expecter) SetRefreshToken(w any, token any) *MockCookieManager_SetRefreshToken_Call {
	return &MockCookieManager_SetRefreshToken_Call{Call: _e.mock.On("SetRefreshToken", w, token)}
}

func (_c *MockCookieManager_SetRefreshToken_Call) Run(run func(w http.ResponseWriter, token string)) *MockCookieManager_SetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCookieManager_SetRefreshToken_Call) Return() *MockCookieManager_SetRefreshToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCookieManager_SetRefreshToken_Call) RunAndReturn(run func(w http.ResponseWriter, token string)) *MockCookieManager_SetRefreshToken_Call {
	_c.Run(run)
	return _c
}
