// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messages_transport_http

import (
	"context"
	"github.com/wrzdx/Nero/internal/core/domain"
	"github.com/wrzdx/Nero/internal/features/messages/service"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessagesService creates a new instance of MockMessagesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessagesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessagesService {
	mock := &MockMessagesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessagesService is an autogenerated mock type for the MessagesService type
type MockMessagesService struct {
	mock.Mock
}

type MockMessagesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessagesService) EXPECT() *MockMessagesService_Expecter {
	return &MockMessagesService_Expecter{mock: &_m.Mock}
}

// DeleteMessage provides a mock function for the type MockMessagesService
func (_mock *MockMessagesService) DeleteMessage(ctx context.Context, command messages_service.DeleteMessageCommand) error {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, messages_service.DeleteMessageCommand) error); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessagesService_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockMessagesService_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - command messages_service.DeleteMessageCommand
func (_e *MockMessagesService_Expecter) DeleteMessage(ctx any, command any) *MockMessagesService_DeleteMessage_Call {
	return &MockMessagesService_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", ctx, command)}
}

func (_c *MockMessagesService_DeleteMessage_Call) Run(run func(ctx context.Context, command messages_service.DeleteMessageCommand)) *MockMessagesService_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 messages_service.DeleteMessageCommand
		if args[1] != nil {
			arg1 = args[1].(messages_service.DeleteMessageCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagesService_DeleteMessage_Call) Return(err error) *MockMessagesService_DeleteMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessagesService_DeleteMessage_Call) RunAndReturn(run func(ctx context.Context, command messages_service.DeleteMessageCommand) error) *MockMessagesService_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// EditMessage provides a mock function for the type MockMessagesService
func (_mock *MockMessagesService) EditMessage(ctx context.Context, command messages_service.UpdateMessageCommand) (domain.Message, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for EditMessage")
	}

	var r0 domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, messages_service.UpdateMessageCommand) (domain.Message, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, messages_service.UpdateMessageCommand) domain.Message); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, messages_service.UpdateMessageCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessagesService_EditMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditMessage'
type MockMessagesService_EditMessage_Call struct {
	*mock.Call
}

// EditMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - command messages_service.UpdateMessageCommand
func (_e *MockMessagesService_Expecter) EditMessage(ctx any, command any) *MockMessagesService_EditMessage_Call {
	return &MockMessagesService_EditMessage_Call{Call: _e.mock.On("EditMessage", ctx, command)}
}

func (_c *MockMessagesService_EditMessage_Call) Run(run func(ctx context.Context, command messages_service.UpdateMessageCommand)) *MockMessagesService_EditMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 messages_service.UpdateMessageCommand
		if args[1] != nil {
			arg1 = args[1].(messages_service.UpdateMessageCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagesService_EditMessage_Call) Return(message domain.Message, err error) *MockMessagesService_EditMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockMessagesService_EditMessage_Call) RunAndReturn(run func(ctx context.Context, command messages_service.UpdateMessageCommand) (domain.Message, error)) *MockMessagesService_EditMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type MockMessagesService
func (_mock *MockMessagesService) GetMessages(ctx context.Context, requesterID uuid.UUID, query messages_service.GetMessagesQuery) (messages_service.MessagePage, error) {
	ret := _mock.Called(ctx, requesterID, query)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 messages_service.MessagePage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, messages_service.GetMessagesQuery) (messages_service.MessagePage, error)); ok {
		return returnFunc(ctx, requesterID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, messages_service.GetMessagesQuery) messages_service.MessagePage); ok {
		r0 = returnFunc(ctx, requesterID, query)
	} else {
		r0 = ret.Get(0).(messages_service.MessagePage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, messages_service.GetMessagesQuery) error); ok {
		r1 = returnFunc(ctx, requesterID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessagesService_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockMessagesService_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - requesterID uuid.UUID
//   - query messages_service.GetMessagesQuery
func (_e *MockMessagesService_Expecter) GetMessages(ctx any, requesterID any, query any) *MockMessagesService_GetMessages_Call {
	return &MockMessagesService_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, requesterID, query)}
}

func (_c *MockMessagesService_GetMessages_Call) Run(run func(ctx context.Context, requesterID uuid.UUID, query messages_service.GetMessagesQuery)) *MockMessagesService_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 messages_service.GetMessagesQuery
		if args[2] != nil {
			arg2 = args[2].(messages_service.GetMessagesQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessagesService_GetMessages_Call) Return(messagePage messages_service.MessagePage, err error) *MockMessagesService_GetMessages_Call {
	_c.Call.Return(messagePage, err)
	return _c
}

func (_c *MockMessagesService_GetMessages_Call) RunAndReturn(run func(ctx context.Context, requesterID uuid.UUID, query messages_service.GetMessagesQuery) (messages_service.MessagePage, error)) *MockMessagesService_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsRead provides a mock function for the type MockMessagesService
func (_mock *MockMessagesService) MarkAsRead(ctx context.Context, command messages_service.MarkAsReadCommand) error {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, messages_service.MarkAsReadCommand) error); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessagesService_MarkAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsRead'
type MockMessagesService_MarkAsRead_Call struct {
	*mock.Call
}

// MarkAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - command messages_service.MarkAsReadCommand
func (_e *MockMessagesService_Expecter) MarkAsRead(ctx any, command any) *MockMessagesService_MarkAsRead_Call {
	return &MockMessagesService_MarkAsRead_Call{Call: _e.mock.On("MarkAsRead", ctx, command)}
}

func (_c *MockMessagesService_MarkAsRead_Call) Run(run func(ctx context.Context, command messages_service.MarkAsReadCommand)) *MockMessagesService_MarkAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 messages_service.MarkAsReadCommand
		if args[1] != nil {
			arg1 = args[1].(messages_service.MarkAsReadCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagesService_MarkAsRead_Call) Return(err error) *MockMessagesService_MarkAsRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessagesService_MarkAsRead_Call) RunAndReturn(run func(ctx context.Context, command messages_service.MarkAsReadCommand) error) *MockMessagesService_MarkAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockMessagesService
func (_mock *MockMessagesService) SendMessage(ctx context.Context, command messages_service.SendMessageCommand) (domain.Message, bool, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 domain.Message
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, messages_service.SendMessageCommand) (domain.Message, bool, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, messages_service.SendMessageCommand) domain.Message); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(domain.Message)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, messages_service.SendMessageCommand) bool); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, messages_service.SendMessageCommand) error); ok {
		r2 = returnFunc(ctx, command)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMessagesService_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockMessagesService_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - command messages_service.SendMessageCommand
func (_e *MockMessagesService_Expecter) SendMessage(ctx any, command any) *MockMessagesService_SendMessage_Call {
	return &MockMessagesService_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, command)}
}

func (_c *MockMessagesService_SendMessage_Call) Run(run func(ctx context.Context, command messages_service.SendMessageCommand)) *MockMessagesService_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 messages_service.SendMessageCommand
		if args[1] != nil {
			arg1 = args[1].(messages_service.SendMessageCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagesService_SendMessage_Call) Return(message domain.Message, b bool, err error) *MockMessagesService_SendMessage_Call {
	_c.Call.Return(message, b, err)
	return _c
}

func (_c *MockMessagesService_SendMessage_Call) RunAndReturn(run func(ctx context.Context, command messages_service.SendMessageCommand) (domain.Message, bool, error)) *MockMessagesService_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
