// Code generated by scripts/build-assets.mjs; DO NOT EDIT.

package web_views

var assetVersions = map[string]string{
	"/static/css/app.css":        "f4d7c22f07555be8",
	"/static/js/auth.js":         "c4838f798661db34",
	"/static/js/app.js":          "7cb6b2ee1621a809",
	"/static/js/participants.js": "fd17eb932c088fbe",
}
