// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package realtime_transport_ws

import (
	"context"
	"github.com/wrzdx/Nero/internal/core/auth"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockParticipantsRepository creates a new instance of MockParticipantsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParticipantsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParticipantsRepository {
	mock := &MockParticipantsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParticipantsRepository is an autogenerated mock type for the ParticipantsRepository type
type MockParticipantsRepository struct {
	mock.Mock
}

type MockParticipantsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParticipantsRepository) EXPECT() *MockParticipantsRepository_Expecter {
	return &MockParticipantsRepository_Expecter{mock: &_m.Mock}
}

// GetParticipants provides a mock function for the type MockParticipantsRepository
func (_mock *MockParticipantsRepository) GetParticipants(ctx context.Context, chatID uuid.UUID) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipants")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParticipantsRepository_GetParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipants'
type MockParticipantsRepository_GetParticipants_Call struct {
	*mock.Call
}

// GetParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID uuid.UUID
func (_e *MockParticipantsRepository_Expecter) GetParticipants(ctx any, chatID any) *MockParticipantsRepository_GetParticipants_Call {
	return &MockParticipantsRepository_GetParticipants_Call{Call: _e.mock.On("GetParticipants", ctx, chatID)}
}

func (_c *MockParticipantsRepository_GetParticipants_Call) Run(run func(ctx context.Context, chatID uuid.UUID)) *MockParticipantsRepository_GetParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParticipantsRepository_GetParticipants_Call) Return(uUIDs []uuid.UUID, err error) *MockParticipantsRepository_GetParticipants_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockParticipantsRepository_GetParticipants_Call) RunAndReturn(run func(ctx context.Context, chatID uuid.UUID) ([]uuid.UUID, error)) *MockParticipantsRepository_GetParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenProvider creates a new instance of MockTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenProvider {
	mock := &MockTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenProvider is an autogenerated mock type for the TokenProvider type
type MockTokenProvider struct {
	mock.Mock
}

type MockTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenProvider) EXPECT() *MockTokenProvider_Expecter {
	return &MockTokenProvider_Expecter{mock: &_m.Mock}
}

// ParseAccessToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) ParseAccessToken(tokenStr string) (auth.ParsedAccessToken, error) {
	ret := _mock.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccessToken")
	}

	var r0 auth.ParsedAccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (auth.ParsedAccessToken, error)); ok {
		return returnFunc(tokenStr)
	}
	if returnFunc, ok := ret.Get(0).(func(string) auth.ParsedAccessToken); ok {
		r0 = returnFunc(tokenStr)
	} else {
		r0 = ret.Get(0).(auth.ParsedAccessToken)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_ParseAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAccessToken'
type MockTokenProvider_ParseAccessToken_Call struct {
	*mock.Call
}

// ParseAccessToken is a helper method to define mock.On call
//   - tokenStr string
func (_e *MockTokenProvider_Expecter) ParseAccessToken(tokenStr any) *MockTokenProvider_ParseAccessToken_Call {
	return &MockTokenProvider_ParseAccessToken_Call{Call: _e.mock.On("ParseAccessToken", tokenStr)}
}

func (_c *MockTokenProvider_ParseAccessToken_Call) Run(run func(tokenStr string)) *MockTokenProvider_ParseAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenProvider_ParseAccessToken_Call) Return(parsedAccessToken auth.ParsedAccessToken, err error) *MockTokenProvider_ParseAccessToken_Call {
	_c.Call.Return(parsedAccessToken, err)
	return _c
}

func (_c *MockTokenProvider_ParseAccessToken_Call) RunAndReturn(run func(tokenStr string) (auth.ParsedAccessToken, error)) *MockTokenProvider_ParseAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
