import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';

// Keep generated HTML and the files shipped in the image on the same version.
const files = ['css/app.css', 'js/auth.js', 'js/app.js', 'js/participants.js'];
const entries = [];
for (const file of files) {
  const bytes = await readFile(new URL(`../web/static/${file}`, import.meta.url));
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 16);
  entries.push(`\t${JSON.stringify(`/static/${file}`)}: ${JSON.stringify(hash)},`);
}
const source = `// Code generated by scripts/build-assets.mjs; DO NOT EDIT.\n\npackage web_views\n\nvar assetVersions = map[string]string{\n${entries.join('\n')}\n}\n`;
await writeFile(new URL('../internal/web/views/assets_generated.go', import.meta.url), source);
